### PR TITLE
Make kernels in CUDA module more asynchronous, add ability to express source for copy as a future value

### PR DESCRIPTION
**Pull request by agrippa**
Some small changes made to HClib in support of the HERDS project.

### CODE REVIEW

**Comment by agrippa** [comment]
@srirajpaul do you have some time to take a look at this diff?

**Comment by srirajpaul** [comment]
@agrippa  Sure. I will take a look.

**Review by srirajpaul — APPROVED** [review]
Looks good.

**Review by srirajpaul — APPROVED** [review]
Looks good.

**Pull request merged**
