### PR TITLE
ISx phases

### PR DESCRIPTION
**Pull request by srki**
Added ISx phases implementations.

### CODE REVIEW

**Review by agrippa — COMMENTED** [review]
There appear to be a few binary files that are included in this pull request (see the very bottom of the list of "Files changed". Could you 'git rm' them? Once that's complete, I'll merge this in.

**Comment by srki** [comment]
Those binary files are deleted. It seems that I deleted binary files that were already in github repository. Should I add them back?

**Comment by agrippa** [comment]
Even if the binaries aren't there in the filesystem, git is still storing metadata to track them because you haven't told it to stop. There's no automatic git-filesystem integration like you have with something like Dropbox.. You can still 'git rm' non-existent files as a way of telling git to not track them anymore. Then git commit and push, and those files should be removed from this pull request.

**Comment by srki** [comment]
When I try to execute the following command
$ git rm objOMP/isx.o_s
I get this error
fatal: pathspec 'test/performance-regression/full-apps/isx/objOMP/isx.o_s' did not match any files

**Comment by agrippa** [comment]
Ah apologies, I believe 'git rm -f' will do it?

**Comment by srki** [comment]
I still get the same error.
$ pwd
/home/sm108/libs/hclib/test/performance-regression/full-apps/isx
$ git rm -f objOMP/isx.o_s
fatal: pathspec 'test/performance-regression/full-apps/isx/objOMP/isx.o_s' did not match any files

**Comment by agrippa** [comment]
Can you send the output of 'git status' by e-mail? And 'git diff isx-phases origin/isx-phases'?

**Pull request merged**
